# Generated by Django 3.2.7 on 2021-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_login_id', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='Information',
        ),
    ]
