# Generated by Django 3.2.7 on 2021-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211012_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
