# Generated by Django 3.2.7 on 2021-11-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211023_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
