# Generated by Django 3.2.7 on 2021-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
        migrations.AddField(
            model_name='message',
            name='receiverId',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='senderId',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
