# Generated by Django 3.2.7 on 2022-04-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='', max_digits=9, null=True),
        ),
    ]
