# Generated by Django 3.2.7 on 2022-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
