# Generated by Django 3.2.7 on 2022-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220225_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
