# Generated by Django 3.2.7 on 2021-11-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
    ]
