# Generated by Django 3.2.7 on 2022-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20220406_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
