# Generated by Django 3.2.7 on 2022-07-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220406_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='latitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.CharField(max_length=200),
        ),
    ]
