# Generated by Django 3.2.7 on 2021-11-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211023_1625'),
        ('board', '0005_board_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(db_column='social_login_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.account'),
        ),
    ]
