# Generated by Django 3.2.7 on 2021-11-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211023_1625'),
        ('board', '0006_alter_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.account'),
        ),
    ]
